include:
  - project: 'fcbank/mobile-app/devops'
    file: 'main.gitlab-ci.yml'
    ref: 'main'

build:
  extends: .builder-kaniko-maven
  only:
    - dev
    - main
  variables:
    DOCKER_FILE: .conf/Dockerfile

deploy-test:
  extends: .base-test-deploy
  only:
    - dev

deploy-prod:
  extends: .deploy-prod
  variables:
    SSH_HOST: 172.23.255.22
  only:
    - main


  